manager/src/Model/Work/Entity/Members/Group/Group.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Group;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="work_members_groups")
 */
class Group
{
    /**
     * @var Id
     * @ORM\Column(type="work_members_group_id")
     * @ORM\Id
     */
    private $id;
    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $name;

    public function __construct(Id $id, string $name)
    {
        $this->id = $id;
        $this->name = $name;
    }

    public function edit(string $name): void
    {
        $this->name = $name;
    }

    public function getId(): Id
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }
}

manager/src/Model/Work/Entity/Members/Group/GroupRepository.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Group;

use App\Model\EntityNotFoundException;
use Doctrine\ORM\EntityManagerInterface;

class GroupRepository
{
    /**
     * @var \Doctrine\ORM\EntityRepository
     */
    private $repo;
    private $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->repo = $em->getRepository(Group::class);
        $this->em = $em;
    }

    public function get(Id $id): Group
    {
        /** @var Group $group */
        if (!$group = $this->repo->find($id->getValue())) {
            throw new EntityNotFoundException('Group is not found.');
        }
        return $group;
    }

    public function add(Group $group): void
    {
        $this->em->persist($group);
    }

    public function remove(Group $group): void
    {
        $this->em->remove($group);
    }
}

manager/src/Model/Work/Entity/Members/Group/Id.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Group;

use Ramsey\Uuid\Uuid;
use Webmozart\Assert\Assert;

class Id
{
    private $value;

    public function __construct(string $value)
    {
        Assert::notEmpty($value);
        $this->value = $value;
    }

    public static function next(): self
    {
        return new self(Uuid::uuid4()->toString());
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}

manager/src/Model/Work/Entity/Members/Group/IdType.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Group;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\GuidType;

class IdType extends GuidType
{
    public const NAME = 'work_members_group_id';

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Id ? $value->getValue() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return !empty($value) ? new Id($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform) : bool
    {
        return true;
    }
}

manager/src/Model/Work/Entity/Members/Member/Email.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Member;

use Webmozart\Assert\Assert;

class Email
{
    private $value;

    public function __construct(string $value)
    {
        Assert::notEmpty($value);
        if (!filter_var($value, FILTER_VALIDATE_EMAIL)) {
            throw new \InvalidArgumentException('Incorrect email.');
        }
        $this->value = mb_strtolower($value);
    }

    public function getValue(): string
    {
        return $this->value;
    }

    public function isEqual(self $other): bool
    {
        return $this->getValue() === $other->getValue();
    }
}

manager/src/Model/Work/Entity/Members/Member/EmailType.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Member;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;

class EmailType extends StringType
{
    public const NAME = 'work_members_member_email';

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return $value instanceof Email ? $value->getValue() : $value;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return !empty($value) ? new Email($value) : null;
    }

    public function getName(): string
    {
        return self::NAME;
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform) : bool
    {
        return true;
    }
}

manager/src/Model/Work/Entity/Members/Member/Name.php
<?php

declare(strict_types=1);

namespace App\Model\Work\Entity\Members\Member;

use Doctrine\ORM\Mapping as ORM;
use Webmozart\Assert\Assert;

/**
 * @ORM\Embeddable
 */
class Name
{
    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $first;
    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $last;

    public function __construct(string $first, string $last)
    {
        Assert::notEmpty($first);
        Assert::notEmpty($last);

        $this->first = $first;
        $this->last = $last;
    }

    public function getFirst(): string
    {
        return $this->first;
    }

    public function getLast(): string
    {
        return $this->last;
    }

    public function getFull(): string
    {
        return $this->first . ' ' . $this->last;
    }
}

manager/src/Controller/Work/Members/GroupsController.php
<?php

declare(strict_types=1);

namespace App\Controller\Work\Members;

use App\Model\Work\Entity\Members\Group\Group;
use App\Model\Work\UseCase\Members\Group\Create;
use App\Model\Work\UseCase\Members\Group\Edit;
use App\Model\Work\UseCase\Members\Group\Remove;
use App\ReadModel\Work\Members\GroupFetcher;
use App\Controller\ErrorHandler;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/work/members/groups", name="work.members.groups")
 * @IsGranted("ROLE_WORK_MANAGE_MEMBERS")
 */
class GroupsController extends AbstractController
{
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("", name="")
     * @param GroupFetcher $fetcher
     * @return Response
     */
    public function index(GroupFetcher $fetcher): Response
    {
        $groups = $fetcher->all();

        return $this->render('app/work/members/groups/index.html.twig', compact('groups'));
    }

    /**
     * @Route("/create", name=".create")
     * @param Request $request
     * @param Create\Handler $handler
     * @return Response
     */
    public function create(Request $request, Create\Handler $handler): Response
    {
        $command = new Create\Command();

        $form = $this->createForm(Create\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('work.members.groups');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/work/members/groups/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name=".edit")
     * @param Group $group
     * @param Request $request
     * @param Edit\Handler $handler
     * @return Response
     */
    public function edit(Group $group, Request $request, Edit\Handler $handler): Response
    {
        $command = Edit\Command::fromGroup($group);

        $form = $this->createForm(Edit\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('work.members.groups.show', ['id' => $group->getId()]);
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/work/members/groups/edit.html.twig', [
            'group' => $group,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name=".delete", methods={"POST"})
     * @param Group $group
     * @param Request $request
     * @param Remove\Handler $handler
     * @return Response
     */
    public function delete(Group $group, Request $request, Remove\Handler $handler): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return $this->redirectToRoute('work.members.groups.show', ['id' => $group->getId()]);
        }

        $command = new Remove\Command($group->getId()->getValue());

        try {
            $handler->handle($command);
            return $this->redirectToRoute('work.members.groups');
        } catch (\DomainException $e) {
            $this->errors->handle($e);
            $this->addFlash('error', $e->getMessage());
        }

        return $this->redirectToRoute('work.members.groups.show', ['id' => $group->getId()]);
    }

    /**
     * @Route("/{id}", name=".show")
     * @return Response
     */
    public function show(): Response
    {
        return $this->redirectToRoute('work.members.groups');
    }
}

manager/src/Controller/Work/Members/MembersController.php
<?php

declare(strict_types=1);

namespace App\Controller\Work\Members;

use App\Annotation\Guid;
use App\Model\User\Entity\User\User;
use App\Model\Work\Entity\Members\Member\Member;
use App\Model\Work\UseCase\Members\Member\Archive;
use App\Model\Work\UseCase\Members\Member\Edit;
use App\Model\Work\UseCase\Members\Member\Reinstate;
use App\Model\Work\UseCase\Members\Member\Create;
use App\Model\Work\UseCase\Members\Member\Move;
use App\ReadModel\Work\Members\Member\Filter;
use App\ReadModel\Work\Members\Member\MemberFetcher;
use App\ReadModel\Work\Projects\Project\DepartmentFetcher;
use App\Controller\ErrorHandler;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/work/members", name="work.members")
 * @IsGranted("ROLE_WORK_MANAGE_MEMBERS")
 */
class MembersController extends AbstractController
{
    private const PER_PAGE = 20;

    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("", name="")
     * @param Request $request
     * @param MemberFetcher $fetcher
     * @return Response
     */
    public function index(Request $request, MemberFetcher $fetcher): Response
    {
        $filter = new Filter\Filter();

        $form = $this->createForm(Filter\Form::class, $filter);
        $form->handleRequest($request);

        $pagination = $fetcher->all(
            $filter,
            $request->query->getInt('page', 1),
            self::PER_PAGE,
            $request->query->get('sort', 'name'),
            $request->query->get('direction', 'asc')
        );

        return $this->render('app/work/members/index.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/create/{id}", name=".create")
     * @param User $user
     * @param Request $request
     * @param MemberFetcher $members
     * @param Create\Handler $handler
     * @return Response
     */
    public function create(User $user, Request $request, MemberFetcher $members, Create\Handler $handler): Response
    {
        if ($members->exists($user->getId()->getValue())) {
            $this->addFlash('error', 'Member already exists.');
            return $this->redirectToRoute('users.show', ['id' => $user->getId()]);
        }

        $command = new Create\Command($user->getId()->getValue());
        $command->firstName = $user->getName()->getFirst();
        $command->lastName = $user->getName()->getLast();
        $command->email = $user->getEmail() ? $user->getEmail()->getValue() : null;

        $form = $this->createForm(Create\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('work.members.show', ['id' => $user->getId()]);
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/work/members/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name=".edit")
     * @param Member $member
     * @param Request $request
     * @param Edit\Handler $handler
     * @return Response
     */
    public function edit(Member $member, Request $request, Edit\Handler $handler): Response
    {
        $command = Edit\Command::fromMember($member);

        $form = $this->createForm(Edit\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/work/members/edit.html.twig', [
            'member' => $member,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/move", name=".move")
     * @param Member $member
     * @param Request $request
     * @param Move\Handler $handler
     * @return Response
     */
    public function move(Member $member, Request $request, Move\Handler $handler): Response
    {
        $command = Move\Command::fromMember($member);

        $form = $this->createForm(Move\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('app/work/members/move.html.twig', [
            'member' => $member,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/archive", name=".archive", methods={"POST"})
     * @param Member $member
     * @param Request $request
     * @param Archive\Handler $handler
     * @return Response
     */
    public function archive(Member $member, Request $request, Archive\Handler $handler): Response
    {
        if (!$this->isCsrfTokenValid('archive', $request->request->get('token'))) {
            return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
        }

        $command = new Archive\Command($member->getId()->getValue());

        try {
            $handler->handle($command);
        } catch (\DomainException $e) {
            $this->errors->handle($e);
            $this->addFlash('error', $e->getMessage());
        }

        return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
    }

    /**
     * @Route("/{id}/reinstate", name=".reinstate", methods={"POST"})
     * @param Member $member
     * @param Request $request
     * @param Reinstate\Handler $handler
     * @return Response
     */
    public function reinstate(Member $member, Request $request, Reinstate\Handler $handler): Response
    {
        if (!$this->isCsrfTokenValid('reinstate', $request->request->get('token'))) {
            return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
        }

        if ($member->getId()->getValue() === $this->getUser()->getId()) {
            $this->addFlash('error', 'Unable to reinstate yourself.');
            return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
        }

        $command = new Reinstate\Command($member->getId()->getValue());

        try {
            $handler->handle($command);
        } catch (\DomainException $e) {
            $this->errors->handle($e);
            $this->addFlash('error', $e->getMessage());
        }

        return $this->redirectToRoute('work.members.show', ['id' => $member->getId()]);
    }

    /**
     * @Route("/{id}", name=".show", requirements={"id"=Guid::PATTERN})
     * @param Member $member
     * @param DepartmentFetcher $fetcher
     * @return Response
     */
    public function show(Member $member, DepartmentFetcher $fetcher): Response
    {
        $departments = $fetcher->allOfMember($member->getId()->getValue());

        return $this->render('app/work/members/show.html.twig', compact('member', 'departments'));
    }
}

manager/templates/app/work/projects/project/settings/members/assign.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work') }}">Work</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects') }}">Projects</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.show', {'id': project.id}) }}">{{ project.name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.settings', {'project_id': project.id}) }}">Settings</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.settings.members', {'project_id': project.id}) }}">Members</a></li>
        <li class="breadcrumb-item active">Assign</li>
    </ol>
{% endblock %}

{% block body %}

    {% include 'app/work/projects/project/_tabs.html.twig' %}

    {% include 'app/work/projects/project/settings/_tabs.html.twig' %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <div>
                <button type="submit" class="btn btn-primary">Assign</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

manager/templates/app/work/projects/project/settings/members/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work') }}">Work</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects') }}">Projects</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.show', {'id': project.id}) }}">{{ project.name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.settings', {'project_id': project.id}) }}">Settings</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.settings.members', {'project_id': project.id}) }}">Members</a></li>
        <li class="breadcrumb-item active">{{ membership.member.name.full }}</li>
    </ol>
{% endblock %}

{% block body %}

    {% include 'app/work/projects/project/_tabs.html.twig' %}

    {% include 'app/work/projects/project/settings/_tabs.html.twig' %}

    <div class="card">
        <div class="card-body">

            {{ form_start(form) }}
            {{ form_widget(form) }}
            <div>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

manager/templates/app/work/projects/project/settings/members/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ project.name }}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ path('home') }}">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work') }}">Work</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects') }}">Projects</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.show', {'id': project.id}) }}">{{ project.name }}</a></li>
        <li class="breadcrumb-item"><a href="{{ path('work.projects.project.settings', {'project_id': project.id}) }}">Settings</a></li>
        <li class="breadcrumb-item active">Members</li>
    </ol>
{% endblock %}

{% block body %}

    {% include 'app/work/projects/project/_tabs.html.twig' %}

    {% include 'app/work/projects/project/settings/_tabs.html.twig' %}

    <div class="controls">
        <a href="{{ path('work.projects.project.settings.members.assign', {'project_id': project.id}) }}" class="btn btn-success">Assign Member</a>
        <a href="{{ path('work.projects.roles') }}" class="btn btn-primary">Roles</a>
    </div>

    <div class="box">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>Name</th>
                <th>Departments</th>
                <th>Roles</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% set token = csrf_token('revoke') %}
            {% for membership in memberships %}
                <tr>
                    <td>
                        <a href="{{ path('work.members.show', {'id': membership.member.id}) }}" target="_blank" class="pull-right"><span class="fa fa-external-link"></span></a>
                        {{ membership.member.name.full }}
                    </td>
                    <td>
                        <ul class="list-unstyled my-0">
                            {% for department in membership.departments %}
                                <li>{{ department.name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul class="list-unstyled my-0">
                            {% for role in membership.roles %}
                                <li>{{ role.name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <div class="d-flex flex-row">
                            <a href="{{ path('work.projects.project.settings.members.edit', {'project_id': project.id, 'member_id': membership.member.id}) }}" class="btn btn-sm btn-primary mr-1"><span class="fa fa-pencil"></span></a>
                            <form action="{{ path('work.projects.project.settings.members.revoke', {'project_id': project.id, 'member_id': membership.member.id}) }}" method="post" onsubmit="return confirm('Are you sure?')">
                                <input type="hidden" name="token" value="{{ token }}" />
                                <button type="submit" class="btn btn-sm btn-danger"><span class="fa fa-times"></span></button>
                            </form>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}